[package]
name = "anthere"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = "2.1.6"
diesel-async = { version = "0.4.1", features = ["postgres"] }
dotenvy = "0.15.7"
serde = { version = "1.0.201", features = ["derive"] }
